---
title: "Lab 6"
author: "Rich Chu, Lorena Mancino, Fatima Gohar"
output: html_notebook
---

# Lab 6: Nothing Is Normal About This!

### Problem 0 

https://github.com/RichChu1/ma350_lab6

## Part I: The Rightful pgauss()

### Problem 1

```{r}
pgauss <- function(x, mean = 0, var = 1){
  cdf <- rep(0, length(x))
  for (i in 1:length(x)){
    cdf[i] <- integrate(f = function(x) dnorm(x, mean = mean, sd = sqrt(var)), lower = -Inf, upper = x[i])[[1]]
  }
  return(cdf)
}
```

### Problem 2

```{r}
pgauss(3,1,2)
pnorm(3, mean = 1, sd = sqrt(2))
```
The values of pgauss and pnorm are the same, meaning that the function works. 


## Part II: What's a Normal Score?

### Problem 3

```{r}
curve(pnorm(x, mean = 5, sd = sqrt(100)), from = -30, to = 30)
abline(v=qnorm(0.25, mean=5, sd=sqrt(100)), col='red')
```

### Problem 4

```{r}
qgauss <- function(q, mean = 0, var = 1){
  quant.function <- rep(0, length(q))
  for (i in 1:length(q)){
    f <- function(x) pgauss(x, mean, var) - q[i]
    quant.function[i] <- uniroot(f, c(mean - 3*sqrt(var), mean+3*sqrt(var)))[[1]]
  }
  return(quant.function)
  
}

```

### Problem 5

```{r}
qgauss(0.25, 5, 100)
qnorm(0.25, mean = 5, sd = sqrt(100))
```
Yes, our answer matches the graphical solution to the problem we found in 3. 


## Part III: What's the Most Likely Mean?

### Problem 6

```{r}

```




















